pipeline {
    agent any
    
    stages {
        stage('Checkout') { 
            steps {
                git credentialsId: "${github_creds}" , url: "${github_repo}" 
            }
        }
        stage('Code Quality Assessment') {
            steps {
                echo 'Code Quality Assessment step'
            }
        }
        stage('Static Application Security step') {
            steps {
                echo 'Static Application Security step'
            }
        }
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
        stage('Software Composition Analysis step') {
            steps {
                echo 'Software Composition Analysis step'
            }
        }            
        stage('Image Vulnerability Assessment step') {
            steps {
                echo 'Image Vulnerability Assessment step'
            }
        }
    }

    post {

      // Email Ext plugin: 
      success {  
        
        emailext (
            subject: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
            body: """<p>SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
              <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
            to: "${emailRecipient}",
            from: "buildNotifications@emailaddress.com"
          )
      }

      failure {
        
        emailext (
            subject: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
            body: """<p>FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
              <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
            to: "${emailRecipient}",
            from: "buildNotifications@emailaddress.com"
          )
      }
  }
}
